### ISSUE TITLE
Defaults from create-config don't match man snapper-configs

### ISSUE THREAD

**Issue by darlingm** [openSUSE/snapper#169]
snapper 0.2.6-2 on arch.

`sudo snapper create-config /`
`sudo snapper get-config`
   BACKGROUND_COMPARISON yes
   EMPTY_PRE_POST_CLEANUP yes
   EMPTY_PRE_POST_MIN_AGE 1800
   FSTYPE btrfs
   NUMBER_CLEANUP yes
   NUMBER_LIMIT 50
   NUMBER_LIMIT_IMPORTANT 10
   NUMBER_MIN_AGE 1800
   SUBVOLUME /
   SYNC_ACL no
   TIMELINE_CLEANUP yes
   TIMELINE_CREATE yes
   TIMELINE_LIMIT_DAILY 10
   TIMELINE_LIMIT_HOURLY 10
   TIMELINE_LIMIT_MONTHLY 10
   TIMELINE_LIMIT_WEEKLY 0
   TIMELINE_LIMIT_YEARLY 10
   TIMELINE_MIN_AGE 1800

But `man snapper-configs` says:
   NUMBER_CLEANUP=boolean... Default value is "no"
   TIMELINE_CREATE=boolean... Default value is "no".
   TIMELINE_CLEANUP=boolean... Default value is "no".
   EMPTY_PRE_POST_CLEANUP=boolean... Default value is "no".

**Comment by aschnell** [comment]
snapper-configs explains the default value of the program, not the config file.

The reason for the different values is: When adding a new feature (thus variable) the default of the programs should be to have the new feature disabled so that users don't get changed behaviour when updating. On the other hand new users should get the new feature thus we enable them in the config-file. I agree that this is not very nice.

I will mention that in the man-page together with an explanation.

**Comment by aschnell** [comment]
I have added a note to the man-page.
