### ISSUE TITLE
snapper create of type pre-post description issue

### ISSUE THREAD

**Issue by subzero01** [openSUSE/snapper#207]
snapper uses the description argument only for the pre snappshot. description for post snapshot is empty. It would be great to have a resulting descripition like "Pre <description>" for pre snapshot and "Post <descprion>" for the post snapshot

**Comment by aschnell** [comment]
The snapshot type is displayed good noticeable with the snapper list command. I do not see how displaying the information twice should help the users. Quite the contrary this will need more space on the screen and the output is already very wide.

**Comment by subzero01** [comment]
So the description is not applied to the post snapshot. This is how it should work? The same description for pre and post is also OK. If I use --description parameter I want to have the description set on both snapshots. Thats the issue.

**Comment by aschnell** [comment]
It is programmed that way that the description is empty one the post snapshot when using "snapper create --command ...".

Whether that is the best practice is another question. I implemented it that way since the pre and post
snapshots are intended belong together so a description on the post snapshot seems unneeded.

In any way, you can change the description of any existing snapshot with snapper.
