### ISSUE TITLE
OBS: key expired in Ubuntu 14.04

### ISSUE THREAD

**Issue by rootbert** [openSUSE/snapper#265]
did not know where to post an issue with opensuse build system. However: The Ubuntu 14.04 Release.key seems to be expired. apt prevents me from upgrading with the message "W: GPG error: http://download.opensuse.org  Release: The following signatures were invalid: KEYEXPIRED 1469025259"

apt-key list: 
pub   2048R/324E6311 2014-05-12 [expired: 2016-07-20]
uid                  filesystems OBS Project <filesystems@build.opensuse.org>

maybe someone could configure the OBS account to use valid keys again (e.g. those of U16.04?). thanks a lot!

**Comment by aschnell** [comment]
My experience with the buildservice is not so extensive so the following may be wrong.

It seems that the key is copied to the download repository whenever the package is released (you can see this by looking at the timestamps of all files). Since the latest snapper does not build on older Ubuntu versions (see https://build.opensuse.org/package/show/filesystems:snapper/snapper) the corresponding repositories are outdated and the key has expired.

So to resolve the 'key expired' issue the build failure has to be solved.

**Comment by aschnell** [comment]
Fixed build for Ubuntu 14.04. The updated Release.key expires 2018-09-27.
