### ISSUE TITLE
reinstalled snapper, removed configs: Failure (org.freedesktop.DBus.Error.NoReply).

### ISSUE THREAD

**Issue by zilexa** [openSUSE/snapper#626]
Only the --version command still works. Any other command gives me this error `Failure (org.freedesktop.DBus.Error.NoReply).` even list -configs. 

Ubuntu 20.10, I replaced a few disks, that is why I removed the configs from /etc/snapper/configs and wanted to create new configs. 

I tried uninstalling snapper (apt autoremove snapper) and reinstall again, after a reboot I still have the same behaviour. Please advise.

**Comment by zilexa** [comment]
May I suggest the cause of this error to be catched by Snapper? If /etc/sysconfig does not exist and I believe uninstalling snapper actually deletes it, when you (re) install snapper, you will hit this error until you manually create that folder. The error does not point in any way in this direction.

**Comment by aschnell** [comment]
The problem here is that snapperd (the daemon started by snapper via dbus) terminated right away since it failed to initialize. I have improved the error handling a bit with https://github.com/openSUSE/snapper/pull/636. But it is far from perfect. Now snapper will not list any configs (since none exists) but creating a config still fails.

In the long run I would like to remove the file /etc/sysconfig/snapper completely and just search for configs in /etc/snapper/configs/.
