### ISSUE TITLE
snapper can neither see nor create configs

### ISSUE THREAD

**Issue by rharish101** [openSUSE/snapper#715]
`snapper list-configs` is showing no configs, even when there are two configs located in `/etc/snapper/configs/`. Additionally, whenever I try to create a config (e.g. `snapper -c test create-config /home`), I get the error:
```
IO Error (fopen failed errno:2 (No such file or directory)).
```

~This started after I updated my Arch Linux system today (2022-05-01). I suspect the culprit is some dependency that was updated. I narrowed it down to the `libelf` update from version 0.186 to 0.187, but even then the error sometimes pops up.~ Turns out the issue was a bogus entry in `/etc/conf.d/snapper`.

**Comment by aschnell** [comment]
Please have a look at /var/log/snapper.log. For most exceptions it shows where in the code they are generated.

**Comment by binary-manu** [comment]
Maybe it's unrelated, but I had a similar issue today on my Arch: `snapper` stopped working after being updated to `v0.10.1-1` (I could still list configs, but creating a snapshot failed). The logs showed an attempt  to access a nonexistent file `/etc/snapper/configs/@`. It turned out I had an extra config name `@` in my `/etc/conf.d/snapper` set for `SNAPPER_CONFIGS`. Removing it restored all functionality.

Hope this helps somehow.

**Comment by rharish101** [comment]
@binary-manu Thanks a lot! It seems that this was the actual issue. `/etc/conf.d/snapper` had an additional config called `boot` in the configs list, and this was causing issues. I verified this by checking `/var/log/snapper.log`, as suggested by @aschnell.

**Comment by aschnell** [comment]
Good to see that you could solve the problem.

I will fix the error handling anyway. Thanks for reporting it.
