### ISSUE TITLE
propagete failures from hooks

### ISSUE THREAD

**Issue by lnussel** [openSUSE/snapper#846]
To be able to boot snapper snapshots with systemd-boot, a [hook script](https://github.com/openSUSE/sdbootutil/blob/main/10-sdbootutil.snapper) is used. It runs when setting a default snapshot to tell the bootloader which one to boot next. If something fails, like eg no kernel or initrd available for that hook script could fail. So far the exit code is not propagated back though. So callers cannot actually know whether a snapshot is good to boot. This is particularly important for transactional-update. If a snapshot cannot be made default it should throw it away.

**Comment by aschnell** [comment]
That is not straight forward: For once there can be several hooks so passing the information with the exit status is not possible. Some detailed report stating which hook succeeded/failed would be needed. And since some hooks are executed in the client and some in the server the server has to pass this report to the client.

I think it is easier for the specific hook to implement some mechanism to pass the required information back to the caller, e.g. via the file system or some message queue.

**Comment by lnussel** [comment]
That's really ugly though. Snapper already returns a exit status if the native code throws an exception AFAICT. So should be possible to make hooks throw an exception too. Doesn't have to be a specific exit code defined by the hook. Just failure in general

**Comment by aschnell** [comment]
Using exceptions to report errors of plugins looks simple at first but stops the normal code flow and can leave behind an inconsistent state (e.g. new empty directory in .snapshots - just tested). Handling all those cases looks complex.

**Comment by aschnell** [comment]
I will have a look. The problem is not that it's rocket science but it affects many layers/functions and I do not want to break the API.

**Comment by aschnell** [comment]
First packages at https://build.opensuse.org/package/show/home:aschnell:snapper/snapper.
