### ISSUE TITLE
bcachefs support

### ISSUE THREAD

**Issue by dim-geo** [openSUSE/snapper#858]
Slowly bcachefs is getting support and stabilizing in kernel. Snapper should be able to support that fs

**Comment by aschnell** [comment]
I have added some support for bcachefs. It is so far only experimental since a few things have to be taken care of (see https://github.com/openSUSE/snapper/blob/master/doc/bcachefs.txt).

Also features like rollback seem currently impossible since bcachefs does not have the concept of a default snapshot like btrfs or anything else in that direction AFAIS.
