### ISSUE TITLE
`loading <n> failed` error logged consistently

### ISSUE THREAD

**Issue by 0x1a8510f2** [openSUSE/snapper#963]
Related: https://github.com/openSUSE/sdbootutil/issues/165

I've been seeing the titular error almost every time I run `zypper dup` as of late, and in the cases mentioned in the linked issue.

I'm on openSUSE Tumbleweed on a Framework 13 laptop.

More details/logs in the linked issue.

**Comment by aschnell** [comment]
For each snapshot snapper keeps a file with metadata, e.g. in /.snapshots/42/info.xml. The error indicates that loading of that file failed. Likely it does not exist. Why it does not exist? Maybe system crashes, file system full during snapshot creation or some other problem.

**Comment by 0x1a8510f2** [comment]
Is there a way to get rid of those error logs?

**Comment by aschnell** [comment]
Yes, remove the snapshot in the directory and the directory itself.

btrfs subvolume delete /.snapshots/42/snapshot
rmdir /.snapshots/42

Maybe the snapshot does not exist. And there could be other files in the directory.

Files in the directory could also explain why the system is in the strange state. It could be that the snapper tried to remove the snapshot but failed removing the directory since it was not empty.

**Comment by 0x1a8510f2** [comment]
Makes sense. Thank you!
